apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - name: nginx
      image: "nginx:1.10.3"
      lifecycle:
        preStop:
          exec:
            command: ["/usr/sbin/nginx","-s","quit"]
      volumeMounts:
        - name: "nginx-proxy-conf"
          mountPath: "/etc/nginx/conf.d"
        - name: "tls-certs"
          mountPath: "/etc/tls"
    - name: hello
      image: gcr.io/google-samples/hello-go-gke:1.0
      ports:
        - name: http
          containerPort: 80
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi" 
  volumes:
    - name: "tls-certs"
      secret:
        secretName: "tls-certs"
    - name: "nginx-proxy-conf"
      configMap:
        name: "nginx-proxy-conf"
        items:
          - key: "proxy.conf"
            path: "nginx/proxy.conf"

